package com.example;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.bean.Goodsinfo;

import com.example.GoodsinfoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig goodsinfoDaoConfig;

    private final GoodsinfoDao goodsinfoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        goodsinfoDaoConfig = daoConfigMap.get(GoodsinfoDao.class).clone();
        goodsinfoDaoConfig.initIdentityScope(type);

        goodsinfoDao = new GoodsinfoDao(goodsinfoDaoConfig, this);

        registerDao(Goodsinfo.class, goodsinfoDao);
    }
    
    public void clear() {
        goodsinfoDaoConfig.clearIdentityScope();
    }

    public GoodsinfoDao getGoodsinfoDao() {
        return goodsinfoDao;
    }

}
