package com.example.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.bean.Judge;
import com.example.bean.LoginReg.LoginInfo;

import com.example.dao.JudgeDao;
import com.example.dao.LoginInfoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig judgeDaoConfig;
    private final DaoConfig loginInfoDaoConfig;

    private final JudgeDao judgeDao;
    private final LoginInfoDao loginInfoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        judgeDaoConfig = daoConfigMap.get(JudgeDao.class).clone();
        judgeDaoConfig.initIdentityScope(type);

        loginInfoDaoConfig = daoConfigMap.get(LoginInfoDao.class).clone();
        loginInfoDaoConfig.initIdentityScope(type);

        judgeDao = new JudgeDao(judgeDaoConfig, this);
        loginInfoDao = new LoginInfoDao(loginInfoDaoConfig, this);

        registerDao(Judge.class, judgeDao);
        registerDao(LoginInfo.class, loginInfoDao);
    }
    
    public void clear() {
        judgeDaoConfig.clearIdentityScope();
        loginInfoDaoConfig.clearIdentityScope();
    }

    public JudgeDao getJudgeDao() {
        return judgeDao;
    }

    public LoginInfoDao getLoginInfoDao() {
        return loginInfoDao;
    }

}
