package com.example.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.example.bean.Judge;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "JUDGE".
*/
public class JudgeDao extends AbstractDao<Judge, Long> {

    public static final String TABLENAME = "JUDGE";

    /**
     * Properties of entity Judge.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, long.class, "id", true, "_id");
        public final static Property Phone = new Property(1, String.class, "phone", false, "PHONE");
        public final static Property Passward = new Property(2, String.class, "passward", false, "PASSWARD");
        public final static Property Ischecked = new Property(3, boolean.class, "ischecked", false, "ISCHECKED");
    }


    public JudgeDao(DaoConfig config) {
        super(config);
    }
    
    public JudgeDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"JUDGE\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL ," + // 0: id
                "\"PHONE\" TEXT," + // 1: phone
                "\"PASSWARD\" TEXT," + // 2: passward
                "\"ISCHECKED\" INTEGER NOT NULL );"); // 3: ischecked
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"JUDGE\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Judge entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getId());
 
        String phone = entity.getPhone();
        if (phone != null) {
            stmt.bindString(2, phone);
        }
 
        String passward = entity.getPassward();
        if (passward != null) {
            stmt.bindString(3, passward);
        }
        stmt.bindLong(4, entity.getIschecked() ? 1L: 0L);
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Judge entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getId());
 
        String phone = entity.getPhone();
        if (phone != null) {
            stmt.bindString(2, phone);
        }
 
        String passward = entity.getPassward();
        if (passward != null) {
            stmt.bindString(3, passward);
        }
        stmt.bindLong(4, entity.getIschecked() ? 1L: 0L);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.getLong(offset + 0);
    }    

    @Override
    public Judge readEntity(Cursor cursor, int offset) {
        Judge entity = new Judge( //
            cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // phone
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // passward
            cursor.getShort(offset + 3) != 0 // ischecked
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Judge entity, int offset) {
        entity.setId(cursor.getLong(offset + 0));
        entity.setPhone(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setPassward(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setIschecked(cursor.getShort(offset + 3) != 0);
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Judge entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Judge entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Judge entity) {
        throw new UnsupportedOperationException("Unsupported for entities with a non-null key");
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
